CREATE DATABASE IF NOT EXISTS copa_db;
USE copa_db ;

CREATE TABLE IF NOT EXISTS selecoes(
	id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    grupo VARCHAR(100) NOT NULL,
    titulos INT NOT NULL,
	criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
    
);

SELECT * FROM selecoes;